apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastisys-test
spec:
  selector:
    matchLabels:
      app: elastisys
  template:
    metadata:
      labels:
        app: elastisys
    spec:
      containers:
      - name: elastisys-test
        image: public.ecr.aws/j4d7t2q3/elastisys-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: elastisys
spec:
  type: LoadBalancer
  selector:
    app: elastisys
  ports:
  - port: 80
    targetPort: 3000